const mongoose = require('mongoose');
const Lesson = require('./models/Lesson');
require('dotenv').config();

const languages = [
  'Spanish', 'French', 'German', 'Italian', 'Portuguese', 'Dutch', 'Swedish', 'Norwegian', 'Danish', 'Polish',
  'Russian', 'Greek', 'Turkish', 'Tamil', 'Hindi', 'Telugu', 'Malayalam', 'Kannada',
  'Japanese', 'Chinese', 'Korean', 'Arabic', 'Thai', 'Vietnamese', 'Indonesian', 'English'
];

// All translations in ASCII-safe romanized form
const tr = {
  Spanish: { hello: 'Hola', good_morning: 'Buenos dias', good_afternoon: 'Buenas tardes', good_evening: 'Buenas noches', good_night: 'Buenas noches', thank_you: 'Gracias', welcome: 'Bienvenido', sorry: 'Lo siento', please: 'Por favor', excuse_me: 'Perdon', father: 'Padre', mother: 'Madre', brother: 'Hermano', sister: 'Hermana', uncle: 'Tio', aunt: 'Tia', grandfather: 'Abuelo', grandmother: 'Abuela', son: 'Hijo', daughter: 'Hija', tea: 'Te', water: 'Agua', food: 'Comida', rice: 'Arroz', milk: 'Leche', sugar: 'Azucar', coffee: 'Cafe', salt: 'Sal', bread: 'Pan', doctor: 'Doctor', teacher: 'Maestro', lawyer: 'Abogado', engineer: 'Ingeniero', police: 'Policia', farmer: 'Agricultor', driver: 'Conductor', chef: 'Chef', nurse: 'Enfermera', apple: 'Manzana', banana: 'Platano', mango: 'Mango', orange: 'Naranja', grapes: 'Uvas', pineapple: 'Pina', watermelon: 'Sandia', papaya: 'Papaya', strawberry: 'Fresa', n1: 'Uno', n2: 'Dos', n3: 'Tres', n4: 'Cuatro', n5: 'Cinco', n6: 'Seis', n7: 'Siete', n8: 'Ocho', n9: 'Nueve', n10: 'Diez', red: 'Rojo', blue: 'Azul', green: 'Verde', yellow: 'Amarillo', black: 'Negro', white: 'Blanco', dog: 'Perro', cat: 'Gato', lion: 'Leon', tiger: 'Tigre', cow: 'Vaca', horse: 'Caballo', how_are_you: 'Como estas', i_am_fine: 'Estoy bien', your_name: 'Como te llamas', where_from: 'De donde eres' },
  French: { hello: 'Bonjour', good_morning: 'Bonjour', good_afternoon: 'Bonne apres-midi', good_evening: 'Bonsoir', good_night: 'Bonne nuit', thank_you: 'Merci', welcome: 'Bienvenue', sorry: 'Desole', please: 'Sil vous plait', excuse_me: 'Excusez-moi', father: 'Pere', mother: 'Mere', brother: 'Frere', sister: 'Soeur', uncle: 'Oncle', aunt: 'Tante', grandfather: 'Grand-pere', grandmother: 'Grand-mere', son: 'Fils', daughter: 'Fille', tea: 'The', water: 'Eau', food: 'Nourriture', rice: 'Riz', milk: 'Lait', sugar: 'Sucre', coffee: 'Cafe', salt: 'Sel', bread: 'Pain', doctor: 'Medecin', teacher: 'Professeur', lawyer: 'Avocat', engineer: 'Ingenieur', police: 'Police', farmer: 'Agriculteur', driver: 'Conducteur', chef: 'Chef', nurse: 'Infirmiere', apple: 'Pomme', banana: 'Banane', mango: 'Mangue', orange: 'Orange', grapes: 'Raisins', pineapple: 'Ananas', watermelon: 'Pasteque', papaya: 'Papaye', strawberry: 'Fraise', n1: 'Un', n2: 'Deux', n3: 'Trois', n4: 'Quatre', n5: 'Cinq', n6: 'Six', n7: 'Sept', n8: 'Huit', n9: 'Neuf', n10: 'Dix', red: 'Rouge', blue: 'Bleu', green: 'Vert', yellow: 'Jaune', black: 'Noir', white: 'Blanc', dog: 'Chien', cat: 'Chat', lion: 'Lion', tiger: 'Tigre', cow: 'Vache', horse: 'Cheval', how_are_you: 'Comment allez-vous', i_am_fine: 'Je vais bien', your_name: 'Comment vous appelez-vous', where_from: 'D ou venez-vous' },
  German: { hello: 'Hallo', good_morning: 'Guten Morgen', good_afternoon: 'Guten Nachmittag', good_evening: 'Guten Abend', good_night: 'Gute Nacht', thank_you: 'Danke', welcome: 'Willkommen', sorry: 'Es tut mir leid', please: 'Bitte', excuse_me: 'Entschuldigung', father: 'Vater', mother: 'Mutter', brother: 'Bruder', sister: 'Schwester', uncle: 'Onkel', aunt: 'Tante', grandfather: 'Grossvater', grandmother: 'Grossmutter', son: 'Sohn', daughter: 'Tochter', tea: 'Tee', water: 'Wasser', food: 'Essen', rice: 'Reis', milk: 'Milch', sugar: 'Zucker', coffee: 'Kaffee', salt: 'Salz', bread: 'Brot', doctor: 'Arzt', teacher: 'Lehrer', lawyer: 'Anwalt', engineer: 'Ingenieur', police: 'Polizei', farmer: 'Bauer', driver: 'Fahrer', chef: 'Koch', nurse: 'Krankenschwester', apple: 'Apfel', banana: 'Banane', mango: 'Mango', orange: 'Orange', grapes: 'Trauben', pineapple: 'Ananas', watermelon: 'Wassermelone', papaya: 'Papaya', strawberry: 'Erdbeere', n1: 'Eins', n2: 'Zwei', n3: 'Drei', n4: 'Vier', n5: 'Funf', n6: 'Sechs', n7: 'Sieben', n8: 'Acht', n9: 'Neun', n10: 'Zehn', red: 'Rot', blue: 'Blau', green: 'Grun', yellow: 'Gelb', black: 'Schwarz', white: 'Weiss', dog: 'Hund', cat: 'Katze', lion: 'Lowe', tiger: 'Tiger', cow: 'Kuh', horse: 'Pferd', how_are_you: 'Wie geht es Ihnen', i_am_fine: 'Mir geht es gut', your_name: 'Wie heissen Sie', where_from: 'Woher kommen Sie' },
  Italian: { hello: 'Ciao', good_morning: 'Buongiorno', good_afternoon: 'Buon pomeriggio', good_evening: 'Buonasera', good_night: 'Buonanotte', thank_you: 'Grazie', welcome: 'Benvenuto', sorry: 'Mi dispiace', please: 'Per favore', excuse_me: 'Mi scusi', father: 'Padre', mother: 'Madre', brother: 'Fratello', sister: 'Sorella', uncle: 'Zio', aunt: 'Zia', grandfather: 'Nonno', grandmother: 'Nonna', son: 'Figlio', daughter: 'Figlia', tea: 'Te', water: 'Acqua', food: 'Cibo', rice: 'Riso', milk: 'Latte', sugar: 'Zucchero', coffee: 'Caffe', salt: 'Sale', bread: 'Pane', doctor: 'Medico', teacher: 'Insegnante', lawyer: 'Avvocato', engineer: 'Ingegnere', police: 'Polizia', farmer: 'Agricoltore', driver: 'Autista', chef: 'Cuoco', nurse: 'Infermiera', apple: 'Mela', banana: 'Banana', mango: 'Mango', orange: 'Arancia', grapes: 'Uva', pineapple: 'Ananas', watermelon: 'Anguria', papaya: 'Papaia', strawberry: 'Fragola', n1: 'Uno', n2: 'Due', n3: 'Tre', n4: 'Quattro', n5: 'Cinque', n6: 'Sei', n7: 'Sette', n8: 'Otto', n9: 'Nove', n10: 'Dieci', red: 'Rosso', blue: 'Blu', green: 'Verde', yellow: 'Giallo', black: 'Nero', white: 'Bianco', dog: 'Cane', cat: 'Gatto', lion: 'Leone', tiger: 'Tigre', cow: 'Mucca', horse: 'Cavallo', how_are_you: 'Come stai', i_am_fine: 'Sto bene', your_name: 'Come ti chiami', where_from: 'Da dove vieni' },
  Portuguese: { hello: 'Ola', good_morning: 'Bom dia', good_afternoon: 'Boa tarde', good_evening: 'Boa noite', good_night: 'Boa noite', thank_you: 'Obrigado', welcome: 'Bem-vindo', sorry: 'Desculpe', please: 'Por favor', excuse_me: 'Com licenca', father: 'Pai', mother: 'Mae', brother: 'Irmao', sister: 'Irma', uncle: 'Tio', aunt: 'Tia', grandfather: 'Avo', grandmother: 'Avo', son: 'Filho', daughter: 'Filha', tea: 'Cha', water: 'Agua', food: 'Comida', rice: 'Arroz', milk: 'Leite', sugar: 'Acucar', coffee: 'Cafe', salt: 'Sal', bread: 'Pao', doctor: 'Medico', teacher: 'Professor', lawyer: 'Advogado', engineer: 'Engenheiro', police: 'Policia', farmer: 'Agricultor', driver: 'Motorista', chef: 'Chef', nurse: 'Enfermeira', apple: 'Maca', banana: 'Banana', mango: 'Manga', orange: 'Laranja', grapes: 'Uvas', pineapple: 'Abacaxi', watermelon: 'Melancia', papaya: 'Mamao', strawberry: 'Morango', n1: 'Um', n2: 'Dois', n3: 'Tres', n4: 'Quatro', n5: 'Cinco', n6: 'Seis', n7: 'Sete', n8: 'Oito', n9: 'Nove', n10: 'Dez', red: 'Vermelho', blue: 'Azul', green: 'Verde', yellow: 'Amarelo', black: 'Preto', white: 'Branco', dog: 'Cachorro', cat: 'Gato', lion: 'Leao', tiger: 'Tigre', cow: 'Vaca', horse: 'Cavalo', how_are_you: 'Como voce esta', i_am_fine: 'Estou bem', your_name: 'Qual e o seu nome', where_from: 'De onde voce e' },
  Dutch: { hello: 'Hallo', good_morning: 'Goedemorgen', good_afternoon: 'Goedemiddag', good_evening: 'Goedenavond', good_night: 'Goedenacht', thank_you: 'Dankjewel', welcome: 'Welkom', sorry: 'Sorry', please: 'Alsjeblieft', excuse_me: 'Excuseer', father: 'Vader', mother: 'Moeder', brother: 'Broer', sister: 'Zus', uncle: 'Oom', aunt: 'Tante', grandfather: 'Opa', grandmother: 'Oma', son: 'Zoon', daughter: 'Dochter', tea: 'Thee', water: 'Water', food: 'Eten', rice: 'Rijst', milk: 'Melk', sugar: 'Suiker', coffee: 'Koffie', salt: 'Zout', bread: 'Brood', doctor: 'Dokter', teacher: 'Leraar', lawyer: 'Advocaat', engineer: 'Ingenieur', police: 'Politie', farmer: 'Boer', driver: 'Bestuurder', chef: 'Kok', nurse: 'Verpleegkundige', apple: 'Appel', banana: 'Banaan', mango: 'Mango', orange: 'Sinaasappel', grapes: 'Druiven', pineapple: 'Ananas', watermelon: 'Watermeloen', papaya: 'Papaja', strawberry: 'Aardbei', n1: 'Een', n2: 'Twee', n3: 'Drie', n4: 'Vier', n5: 'Vijf', n6: 'Zes', n7: 'Zeven', n8: 'Acht', n9: 'Negen', n10: 'Tien', red: 'Rood', blue: 'Blauw', green: 'Groen', yellow: 'Geel', black: 'Zwart', white: 'Wit', dog: 'Hond', cat: 'Kat', lion: 'Leeuw', tiger: 'Tijger', cow: 'Koe', horse: 'Paard', how_are_you: 'Hoe gaat het', i_am_fine: 'Het gaat goed', your_name: 'Hoe heet jij', where_from: 'Waar kom jij vandaan' },
  Swedish: { hello: 'Hej', good_morning: 'God morgon', good_afternoon: 'God eftermiddag', good_evening: 'God kvall', good_night: 'God natt', thank_you: 'Tack', welcome: 'Valkommen', sorry: 'Forlat', please: 'Snalla', excuse_me: 'Ursakta', father: 'Far', mother: 'Mor', brother: 'Bror', sister: 'Syster', uncle: 'Farbror', aunt: 'Faster', grandfather: 'Morfar', grandmother: 'Mormor', son: 'Son', daughter: 'Dotter', tea: 'Te', water: 'Vatten', food: 'Mat', rice: 'Ris', milk: 'Mjolk', sugar: 'Socker', coffee: 'Kaffe', salt: 'Salt', bread: 'Brod', doctor: 'Lakare', teacher: 'Larare', lawyer: 'Advokat', engineer: 'Ingenjor', police: 'Polis', farmer: 'Bonde', driver: 'Forare', chef: 'Kock', nurse: 'Sjukskoterska', apple: 'Apple', banana: 'Banan', mango: 'Mango', orange: 'Apelsin', grapes: 'Druvor', pineapple: 'Ananas', watermelon: 'Vattenmelon', papaya: 'Papaya', strawberry: 'Jordgubbe', n1: 'En', n2: 'Tva', n3: 'Tre', n4: 'Fyra', n5: 'Fem', n6: 'Sex', n7: 'Sju', n8: 'Atta', n9: 'Nio', n10: 'Tio', red: 'Rod', blue: 'Bla', green: 'Gron', yellow: 'Gul', black: 'Svart', white: 'Vit', dog: 'Hund', cat: 'Katt', lion: 'Lejon', tiger: 'Tiger', cow: 'Ko', horse: 'Hast', how_are_you: 'Hur mar du', i_am_fine: 'Jag mar bra', your_name: 'Vad heter du', where_from: 'Vart kommer du ifran' },
  Norwegian: { hello: 'Hei', good_morning: 'God morgen', good_afternoon: 'God ettermiddag', good_evening: 'God kveld', good_night: 'God natt', thank_you: 'Takk', welcome: 'Velkommen', sorry: 'Beklager', please: 'Vaer sa snill', excuse_me: 'Unnskyld', father: 'Far', mother: 'Mor', brother: 'Bror', sister: 'Soster', uncle: 'Onkel', aunt: 'Tante', grandfather: 'Bestefar', grandmother: 'Bestemor', son: 'Son', daughter: 'Datter', tea: 'Te', water: 'Vann', food: 'Mat', rice: 'Ris', milk: 'Melk', sugar: 'Sukker', coffee: 'Kaffe', salt: 'Salt', bread: 'Brod', doctor: 'Lege', teacher: 'Laerer', lawyer: 'Advokat', engineer: 'Ingenior', police: 'Politi', farmer: 'Bonde', driver: 'Sjafur', chef: 'Kokk', nurse: 'Sykepleier', apple: 'Eple', banana: 'Banan', mango: 'Mango', orange: 'Appelsin', grapes: 'Druer', pineapple: 'Ananas', watermelon: 'Vannmelon', papaya: 'Papaya', strawberry: 'Jordbaer', n1: 'En', n2: 'To', n3: 'Tre', n4: 'Fire', n5: 'Fem', n6: 'Seks', n7: 'Sju', n8: 'Atte', n9: 'Ni', n10: 'Ti', red: 'Rod', blue: 'Bla', green: 'Gronn', yellow: 'Gul', black: 'Svart', white: 'Hvit', dog: 'Hund', cat: 'Katt', lion: 'Loke', tiger: 'Tiger', cow: 'Ku', horse: 'Hest', how_are_you: 'Hvordan har du det', i_am_fine: 'Jeg har det bra', your_name: 'Hva heter du', where_from: 'Hvor er du fra' },
  Danish: { hello: 'Hej', good_morning: 'God morgen', good_afternoon: 'God eftermiddag', good_evening: 'God aften', good_night: 'God nat', thank_you: 'Tak', welcome: 'Velkommen', sorry: 'Undskyld', please: 'Vaer saa venlig', excuse_me: 'Undskyld', father: 'Far', mother: 'Mor', brother: 'Bror', sister: 'Soster', uncle: 'Onkel', aunt: 'Tante', grandfather: 'Bedstefar', grandmother: 'Bedstemor', son: 'Son', daughter: 'Datter', tea: 'Te', water: 'Vand', food: 'Mad', rice: 'Ris', milk: 'Maelk', sugar: 'Sukker', coffee: 'Kaffe', salt: 'Salt', bread: 'Brod', doctor: 'Laege', teacher: 'Laerer', lawyer: 'Advokat', engineer: 'Ingenior', police: 'Politi', farmer: 'Landmand', driver: 'Chauffur', chef: 'Kok', nurse: 'Sygeplejerske', apple: 'Aeble', banana: 'Banan', mango: 'Mango', orange: 'Appelsin', grapes: 'Druer', pineapple: 'Ananas', watermelon: 'Vandmelon', papaya: 'Papaya', strawberry: 'Jordbjaer', n1: 'En', n2: 'To', n3: 'Tre', n4: 'Fire', n5: 'Fem', n6: 'Seks', n7: 'Syv', n8: 'Otte', n9: 'Ni', n10: 'Ti', red: 'Rod', blue: 'Bla', green: 'Gron', yellow: 'Gul', black: 'Sort', white: 'Hvid', dog: 'Hund', cat: 'Kat', lion: 'Love', tiger: 'Tiger', cow: 'Ko', horse: 'Hest', how_are_you: 'Hvordan har du det', i_am_fine: 'Jeg har det godt', your_name: 'Hvad hedder du', where_from: 'Hvor er du fra' }
};
tr.Polish = { hello: 'Czesc', good_morning: 'Dzien dobry', good_afternoon: 'Dzien dobry', good_evening: 'Dobry wieczor', good_night: 'Dobranoc', thank_you: 'Dziekuje', welcome: 'Witamy', sorry: 'Przepraszam', please: 'Prosze', excuse_me: 'Przepraszam', father: 'Ojciec', mother: 'Matka', brother: 'Brat', sister: 'Siostra', uncle: 'Wujek', aunt: 'Ciotka', grandfather: 'Dziadek', grandmother: 'Babcia', son: 'Syn', daughter: 'Corka', tea: 'Herbata', water: 'Woda', food: 'Jedzenie', rice: 'Ryz', milk: 'Mleko', sugar: 'Cukier', coffee: 'Kawa', salt: 'Sol', bread: 'Chleb', doctor: 'Lekarz', teacher: 'Nauczyciel', lawyer: 'Prawnik', engineer: 'Inzynier', police: 'Policja', farmer: 'Rolnik', driver: 'Kierowca', chef: 'Kucharz', nurse: 'Pielegniarka', apple: 'Jablko', banana: 'Banan', mango: 'Mango', orange: 'Pomarancza', grapes: 'Winogrona', pineapple: 'Ananas', watermelon: 'Arbuz', papaya: 'Papaja', strawberry: 'Truskawka', n1: 'Jeden', n2: 'Dwa', n3: 'Trzy', n4: 'Cztery', n5: 'Piec', n6: 'Szesc', n7: 'Siedem', n8: 'Osiem', n9: 'Dziewiec', n10: 'Dziesiec', red: 'Czerwony', blue: 'Niebieski', green: 'Zielony', yellow: 'Zolty', black: 'Czarny', white: 'Bialy', dog: 'Pies', cat: 'Kot', lion: 'Lew', tiger: 'Tygrys', cow: 'Krowa', horse: 'Kon', how_are_you: 'Jak sie masz', i_am_fine: 'Mam sie dobrze', your_name: 'Jak masz na imie', where_from: 'Skad jestes' };
tr.Russian = { hello: 'Privet', good_morning: 'Dobroye utro', good_afternoon: 'Dobryy den', good_evening: 'Dobryy vecher', good_night: 'Spokoinoy nochi', thank_you: 'Spasibo', welcome: 'Dobro pozhalovat', sorry: 'Izvinite', please: 'Pozhaluysta', excuse_me: 'Izvinite', father: 'Otets', mother: 'Mat', brother: 'Brat', sister: 'Sestra', uncle: 'Dyadya', aunt: 'Tyotya', grandfather: 'Dedushka', grandmother: 'Babushka', son: 'Syn', daughter: 'Doch', tea: 'Chay', water: 'Voda', food: 'Yeda', rice: 'Ris', milk: 'Moloko', sugar: 'Sakhar', coffee: 'Kofe', salt: 'Sol', bread: 'Khleb', doctor: 'Vrach', teacher: 'Uchitel', lawyer: 'Advokat', engineer: 'Inzhener', police: 'Politsiya', farmer: 'Fermer', driver: 'Voditel', chef: 'Povar', nurse: 'Medsestra', apple: 'Yabloko', banana: 'Banan', mango: 'Mango', orange: 'Apelsin', grapes: 'Vinograd', pineapple: 'Ananas', watermelon: 'Arbuz', papaya: 'Papaya', strawberry: 'Klubnika', n1: 'Odin', n2: 'Dva', n3: 'Tri', n4: 'Chetyre', n5: 'Pyat', n6: 'Shest', n7: 'Sem', n8: 'Vosem', n9: 'Devyat', n10: 'Desyat', red: 'Krasnyy', blue: 'Siniy', green: 'Zelyonyy', yellow: 'Zholtyy', black: 'Chornyy', white: 'Belyy', dog: 'Sobaka', cat: 'Koshka', lion: 'Lev', tiger: 'Tigr', cow: 'Korova', horse: 'Loshad', how_are_you: 'Kak vy', i_am_fine: 'Ya v poryadke', your_name: 'Kak vas zovut', where_from: 'Otkuda vy' };
tr.Greek = { hello: 'Yia sas', good_morning: 'Kalimera', good_afternoon: 'Kali imera', good_evening: 'Kalispera', good_night: 'Kalinychta', thank_you: 'Efcharisto', welcome: 'Kalosirthate', sorry: 'Signomi', please: 'Parakalo', excuse_me: 'Me sinchoreite', father: 'Pateras', mother: 'Mitera', brother: 'Aderfos', sister: 'Aderfi', uncle: 'Theios', aunt: 'Theia', grandfather: 'Pappous', grandmother: 'Yiayia', son: 'Gios', daughter: 'Kori', tea: 'Tsai', water: 'Nero', food: 'Fagito', rice: 'Ryzi', milk: 'Gala', sugar: 'Zahari', coffee: 'Kafe', salt: 'Alati', bread: 'Psomi', doctor: 'Giatros', teacher: 'Daskalos', lawyer: 'Dikigoros', engineer: 'Michanikos', police: 'Astynomia', farmer: 'Agrotis', driver: 'Odigos', chef: 'Magiras', nurse: 'Nosokoma', apple: 'Milo', banana: 'Banana', mango: 'Mango', orange: 'Portokali', grapes: 'Stafylia', pineapple: 'Ananas', watermelon: 'Karpouzi', papaya: 'Papaya', strawberry: 'Fraoula', n1: 'Ena', n2: 'Dio', n3: 'Tria', n4: 'Tessera', n5: 'Pente', n6: 'Exi', n7: 'Epta', n8: 'Okto', n9: 'Ennea', n10: 'Deka', red: 'Kokkino', blue: 'Ble', green: 'Prasino', yellow: 'Kitrino', black: 'Mavro', white: 'Aspro', dog: 'Skylos', cat: 'Gata', lion: 'Leontari', tiger: 'Tigris', cow: 'Agelada', horse: 'Alogo', how_are_you: 'Pos eisai', i_am_fine: 'Eimai kala', your_name: 'Pos se lene', where_from: 'Apo pou eisai' };
tr.Turkish = { hello: 'Merhaba', good_morning: 'Gunaydin', good_afternoon: 'Iyi gunler', good_evening: 'Iyi aksamlar', good_night: 'Iyi geceler', thank_you: 'Tesekkurler', welcome: 'Hosgeldiniz', sorry: 'Uzgunum', please: 'Lutfen', excuse_me: 'Ozur dilerim', father: 'Baba', mother: 'Anne', brother: 'Agabey', sister: 'Abla', uncle: 'Amca', aunt: 'Teyze', grandfather: 'Dede', grandmother: 'Buyukanne', son: 'Ogul', daughter: 'Kiz', tea: 'Cay', water: 'Su', food: 'Yemek', rice: 'Pilav', milk: 'Sut', sugar: 'Seker', coffee: 'Kahve', salt: 'Tuz', bread: 'Ekmek', doctor: 'Doktor', teacher: 'Ogretmen', lawyer: 'Avukat', engineer: 'Muhendis', police: 'Polis', farmer: 'Ciftci', driver: 'Sofor', chef: 'Asci', nurse: 'Hemsire', apple: 'Elma', banana: 'Muz', mango: 'Mango', orange: 'Portakal', grapes: 'Uzum', pineapple: 'Ananas', watermelon: 'Karpuz', papaya: 'Papaya', strawberry: 'Cilek', n1: 'Bir', n2: 'Iki', n3: 'Uc', n4: 'Dort', n5: 'Bes', n6: 'Alti', n7: 'Yedi', n8: 'Sekiz', n9: 'Dokuz', n10: 'On', red: 'Kirmizi', blue: 'Mavi', green: 'Yesil', yellow: 'Sari', black: 'Siyah', white: 'Beyaz', dog: 'Kopek', cat: 'Kedi', lion: 'Aslan', tiger: 'Kaplan', cow: 'Inek', horse: 'At', how_are_you: 'Nasilsiniz', i_am_fine: 'Iyiyim', your_name: 'Adiniz ne', where_from: 'Nerelisiniz' };
tr.Tamil = { hello: 'Vanakkam', good_morning: 'Kalai Vanakkam', good_afternoon: 'Mathiya Vanakkam', good_evening: 'Malai Vanakkam', good_night: 'Iravu Vanakkam', thank_you: 'Nandri', welcome: 'Varaverkirom', sorry: 'Mannikkavum', please: 'Thayavuseydhu', excuse_me: 'Mannikkavum', father: 'Appa', mother: 'Amma', brother: 'Annan', sister: 'Akka', uncle: 'Mama', aunt: 'Atthai', grandfather: 'Thatha', grandmother: 'Paati', son: 'Magan', daughter: 'Magal', tea: 'Thenir', water: 'Thanneer', food: 'Unavu', rice: 'Soru', milk: 'Paal', sugar: 'Sarkarai', coffee: 'Kaapi', salt: 'Uppu', bread: 'Rotti', doctor: 'Maruthuvar', teacher: 'Aasiriyar', lawyer: 'Valakkaringar', engineer: 'Poriyalar', police: 'Kaavalar', farmer: 'Vivasaayi', driver: 'Ottunar', chef: 'Samaiyalkarar', nurse: 'Seviliyar', apple: 'Aapil', banana: 'Valaippazham', mango: 'Maampazham', orange: 'Aranju', grapes: 'Thiraatchai', pineapple: 'Annasi', watermelon: 'Tharpoosani', papaya: 'Pappali', strawberry: 'Strawberry', n1: 'Ondru', n2: 'Irandu', n3: 'Moondru', n4: 'Nangu', n5: 'Ainthu', n6: 'Aaru', n7: 'Ezhu', n8: 'Ettu', n9: 'Onbadhu', n10: 'Pathu', red: 'Sivappu', blue: 'Neelam', green: 'Pachhai', yellow: 'Manjal', black: 'Karuppu', white: 'Vellai', dog: 'Nai', cat: 'Poonai', lion: 'Singam', tiger: 'Puli', cow: 'Pasu', horse: 'Kutharai', how_are_you: 'Eppadi irukkiirkal', i_am_fine: 'Nalamaga irukkiren', your_name: 'Peyar enna', where_from: 'Engirundhu vandheergal' };
tr.Hindi = { hello: 'Namaste', good_morning: 'Suprabhat', good_afternoon: 'Namaskar', good_evening: 'Shubh Sandhya', good_night: 'Shubh Ratri', thank_you: 'Dhanyavad', welcome: 'Swagat hai', sorry: 'Kshama karo', please: 'Kripaya', excuse_me: 'Maaf karo', father: 'Pita', mother: 'Maa', brother: 'Bhai', sister: 'Behen', uncle: 'Chacha', aunt: 'Chachi', grandfather: 'Dada', grandmother: 'Dadi', son: 'Beta', daughter: 'Beti', tea: 'Chai', water: 'Paani', food: 'Khana', rice: 'Chawal', milk: 'Doodh', sugar: 'Cheeni', coffee: 'Coffee', salt: 'Namak', bread: 'Roti', doctor: 'Doctor', teacher: 'Adhyapak', lawyer: 'Vakeel', engineer: 'Abhiyanta', police: 'Police', farmer: 'Kisaan', driver: 'Chalak', chef: 'Rasoiya', nurse: 'Nurse', apple: 'Seb', banana: 'Kela', mango: 'Aam', orange: 'Santra', grapes: 'Angoor', pineapple: 'Ananas', watermelon: 'Tarbooz', papaya: 'Papita', strawberry: 'Strawberry', n1: 'Ek', n2: 'Do', n3: 'Teen', n4: 'Char', n5: 'Panch', n6: 'Chhah', n7: 'Saat', n8: 'Aath', n9: 'Nau', n10: 'Das', red: 'Lal', blue: 'Neela', green: 'Hara', yellow: 'Peela', black: 'Kaala', white: 'Safed', dog: 'Kutta', cat: 'Billi', lion: 'Sher', tiger: 'Bagh', cow: 'Gay', horse: 'Ghoda', how_are_you: 'Aap kaise hain', i_am_fine: 'Main theek hoon', your_name: 'Aapka naam kya hai', where_from: 'Aap kahaan se hain' };
tr.Telugu = { hello: 'Namaskaram', good_morning: 'Shubhodayam', good_afternoon: 'Shubha Madhyanham', good_evening: 'Shubha Sayantram', good_night: 'Shubha Ratri', thank_you: 'Dhanyavadalu', welcome: 'Swagatam', sorry: 'Kshamimpandi', please: 'Dayachesi', excuse_me: 'Kshamimpandi', father: 'Nanna', mother: 'Amma', brother: 'Anna', sister: 'Akka', uncle: 'Babai', aunt: 'Atta', grandfather: 'Tata', grandmother: 'Nana', son: 'Abbayi', daughter: 'Ammayi', tea: 'Chaaya', water: 'Neellu', food: 'Tinubadam', rice: 'Annam', milk: 'Paalu', sugar: 'Chekkera', coffee: 'Coffee', salt: 'Uppu', bread: 'Rotti', doctor: 'Vaidyudu', teacher: 'Upadhyayudu', lawyer: 'Nyayavadi', engineer: 'Injineer', police: 'Police', farmer: 'Raithu', driver: 'Driver', chef: 'Vantavadu', nurse: 'Nurse', apple: 'Apple', banana: 'Aratipandu', mango: 'Mamidipandu', orange: 'Nimbapandu', grapes: 'Draksha', pineapple: 'Anasa', watermelon: 'Pucchakaya', papaya: 'Boppayi', strawberry: 'Strawberry', n1: 'Okati', n2: 'Rendu', n3: 'Moodu', n4: 'Naalugu', n5: 'Aidu', n6: 'Aaru', n7: 'Edu', n8: 'Enimidi', n9: 'Tommidi', n10: 'Padi', red: 'Errupu', blue: 'Neelam', green: 'Pacha', yellow: 'Pasupu', black: 'Nallani', white: 'Telupu', dog: 'Kukka', cat: 'Pilli', lion: 'Simham', tiger: 'Puli', cow: 'Pasuvu', horse: 'Gurram', how_are_you: 'Ela unnaru', i_am_fine: 'Nenu baagunnanu', your_name: 'Meeru peru enti', where_from: 'Meeru ekkadi nundi' };
tr.Malayalam = { hello: 'Namaskaram', good_morning: 'Suprabhatam', good_afternoon: 'Shubha Madhyahnam', good_evening: 'Shubha Sayahnam', good_night: 'Shubha Raatri', thank_you: 'Nandi', welcome: 'Swagatam', sorry: 'Kshamikkuka', please: 'Dayavayi', excuse_me: 'Kshamikkuka', father: 'Achan', mother: 'Amma', brother: 'Jyeshthan', sister: 'Chechi', uncle: 'Ammavan', aunt: 'Ammaayi', grandfather: 'Appupan', grandmother: 'Ammumma', son: 'Makan', daughter: 'Maku', tea: 'Chaya', water: 'Vellam', food: 'Bhakshanam', rice: 'Choru', milk: 'Paal', sugar: 'Panjasara', coffee: 'Coffee', salt: 'Uppu', bread: 'Bread', doctor: 'Doctor', teacher: 'Adhyapakan', lawyer: 'Avakasi', engineer: 'Injineer', police: 'Police', farmer: 'Krishikan', driver: 'Driver', chef: 'Pacharakaran', nurse: 'Nurse', apple: 'Apple', banana: 'Vazhapazham', mango: 'Maanga', orange: 'Naranga', grapes: 'Munthiri', pineapple: 'Kaitha chakka', watermelon: 'Tharbooz', papaya: 'Papaya', strawberry: 'Strawberry', n1: 'Onnu', n2: 'Randu', n3: 'Moonnu', n4: 'Naalu', n5: 'Anchu', n6: 'Aaru', n7: 'Ezhu', n8: 'Ettu', n9: 'Ombatu', n10: 'Pathu', red: 'Chuvappu', blue: 'Neela', green: 'Pacha', yellow: 'Manja', black: 'Karupp', white: 'Vella', dog: 'Naay', cat: 'Poocha', lion: 'Simham', tiger: 'Puli', cow: 'Pasu', horse: 'Kudira', how_are_you: 'Saukaryamo', i_am_fine: 'Saukaryam', your_name: 'Peru enthaanu', where_from: 'Evide ninnu' };
tr.Kannada = { hello: 'Namaskara', good_morning: 'Shubha Munjane', good_afternoon: 'Shubha Madhyahna', good_evening: 'Shubha Sanje', good_night: 'Shubha Ratri', thank_you: 'Dhanyavada', welcome: 'Swagatave', sorry: 'Kshamisiri', please: 'Dayavittu', excuse_me: 'Kshamisi', father: 'Tande', mother: 'Taayi', brother: 'Annare', sister: 'Akka', uncle: 'Doda Anna', aunt: 'Doddamma', grandfather: 'Ajja', grandmother: 'Ajji', son: 'Maga', daughter: 'Magalu', tea: 'Chai', water: 'Neeru', food: 'Aahara', rice: 'Anna', milk: 'Haalu', sugar: 'Sakkare', coffee: 'Coffee', salt: 'Uppu', bread: 'Bread', doctor: 'Vaidya', teacher: 'Shikshaka', lawyer: 'Nyayavadhi', engineer: 'Injineeru', police: 'Police', farmer: 'Raita', driver: 'Driver', chef: 'Annapurna', nurse: 'Nurse', apple: 'Sebu', banana: 'Baale Hannu', mango: 'Maavina Hannu', orange: 'Kittale', grapes: 'Drakshi', pineapple: 'Ananas', watermelon: 'Kallangadi', papaya: 'Papaya', strawberry: 'Strawberry', n1: 'Ondu', n2: 'Eradu', n3: 'Mooru', n4: 'Naalku', n5: 'Aidu', n6: 'Aaru', n7: 'Elu', n8: 'Entu', n9: 'Ombattu', n10: 'Hattu', red: 'Kempu', blue: 'Neeli', green: 'Hasiru', yellow: 'Haladi', black: 'Kaaru', white: 'Bili', dog: 'Naayi', cat: 'Bekku', lion: 'Simha', tiger: 'Huli', cow: 'Hasu', horse: 'Kudure', how_are_you: 'Hegiddiri', i_am_fine: 'Chennagiddene', your_name: 'Nimma hesaru enu', where_from: 'Nimma uru yaadhadu' };
tr.Japanese = { hello: 'Konnichiwa', good_morning: 'Ohayou Gozaimasu', good_afternoon: 'Konnichiwa', good_evening: 'Konbanwa', good_night: 'Oyasumi Nasai', thank_you: 'Arigatou', welcome: 'Youkoso', sorry: 'Sumimasen', please: 'Douzo', excuse_me: 'Sumimasen', father: 'Otousan', mother: 'Okaasan', brother: 'Oniisan', sister: 'Oneesan', uncle: 'Ojisan', aunt: 'Obasan', grandfather: 'Ojiisan', grandmother: 'Obaasan', son: 'Musuko', daughter: 'Musume', tea: 'Ocha', water: 'Mizu', food: 'Tabemono', rice: 'Gohan', milk: 'Gyuunyuu', sugar: 'Satou', coffee: 'Koohii', salt: 'Shio', bread: 'Pan', doctor: 'Isha', teacher: 'Sensei', lawyer: 'Bengoshi', engineer: 'Enjinia', police: 'Keisatsu', farmer: 'Nouka', driver: 'Untenshu', chef: 'Shefu', nurse: 'Kangoshi', apple: 'Ringo', banana: 'Banana', mango: 'Mangoo', orange: 'Orenji', grapes: 'Budou', pineapple: 'Painappuru', watermelon: 'Suika', papaya: 'Papaia', strawberry: 'Ichigo', n1: 'Ichi', n2: 'Ni', n3: 'San', n4: 'Shi', n5: 'Go', n6: 'Roku', n7: 'Nana', n8: 'Hachi', n9: 'Ku', n10: 'Juu', red: 'Aka', blue: 'Ao', green: 'Midori', yellow: 'Kiiro', black: 'Kuro', white: 'Shiro', dog: 'Inu', cat: 'Neko', lion: 'Raion', tiger: 'Tora', cow: 'Ushi', horse: 'Uma', how_are_you: 'Ogenki desu ka', i_am_fine: 'Genki desu', your_name: 'Onamae wa', where_from: 'Doko kara kimashita ka' };
tr.Chinese = { hello: 'Ni hao', good_morning: 'Zaoshang hao', good_afternoon: 'Xiawu hao', good_evening: 'Wanshang hao', good_night: 'Wanan', thank_you: 'Xie xie', welcome: 'Huanying', sorry: 'Duibuqi', please: 'Qing', excuse_me: 'Laojia', father: 'Fuqin', mother: 'Muqin', brother: 'Xiongdi', sister: 'Jiemei', uncle: 'Shushu', aunt: 'Ayi', grandfather: 'Zufu', grandmother: 'Zumu', son: 'Erzi', daughter: 'Nuer', tea: 'Cha', water: 'Shui', food: 'Shiwu', rice: 'Mifan', milk: 'Niunai', sugar: 'Tang', coffee: 'Kafei', salt: 'Yan', bread: 'Mianbao', doctor: 'Yisheng', teacher: 'Laoshi', lawyer: 'Lvshi', engineer: 'Gongchengshi', police: 'Jingcha', farmer: 'Nongmin', driver: 'Siji', chef: 'Chushi', nurse: 'Hushi', apple: 'Pingguo', banana: 'Xiangjiao', mango: 'Mangguo', orange: 'Chengzi', grapes: 'Putao', pineapple: 'Boluo', watermelon: 'Xigua', papaya: 'Mugua', strawberry: 'Caomei', n1: 'Yi', n2: 'Er', n3: 'San', n4: 'Si', n5: 'Wu', n6: 'Liu', n7: 'Qi', n8: 'Ba', n9: 'Jiu', n10: 'Shi', red: 'Hongse', blue: 'Lanse', green: 'Lvse', yellow: 'Huangse', black: 'Heise', white: 'Baise', dog: 'Gou', cat: 'Mao', lion: 'Shizi', tiger: 'Laohu', cow: 'Niu', horse: 'Ma', how_are_you: 'Ni hao ma', i_am_fine: 'Wo hen hao', your_name: 'Ni jiao shenme', where_from: 'Ni cong nali lai' };
tr.Korean = { hello: 'Annyeonghaseyo', good_morning: 'Joeun achim', good_afternoon: 'Joeun ohu', good_evening: 'Joeun jeonyeok', good_night: 'Jal jayo', thank_you: 'Gamsahamnida', welcome: 'Hwanyeonghamnida', sorry: 'Joesonghamnida', please: 'Jebal', excuse_me: 'Sillyehamnida', father: 'Abeoji', mother: 'Eomeoni', brother: 'Hyeong', sister: 'Nuna', uncle: 'Samchon', aunt: 'Imo', grandfather: 'Harabeoji', grandmother: 'Halmeoni', son: 'Adeul', daughter: 'Ttal', tea: 'Cha', water: 'Mul', food: 'Eumsik', rice: 'Bap', milk: 'Uyu', sugar: 'Seoltang', coffee: 'Keopi', salt: 'Sogeum', bread: 'Ppang', doctor: 'Uisa', teacher: 'Seonsaengnim', lawyer: 'Byeonhosa', engineer: 'Enjinieo', police: 'Gyeongchal', farmer: 'Nongbu', driver: 'Unjeonsa', chef: 'Yorisa', nurse: 'Ganhosa', apple: 'Sagwa', banana: 'Banana', mango: 'Manggo', orange: 'Orenji', grapes: 'Podo', pineapple: 'Painaepeul', watermelon: 'Subak', papaya: 'Papaya', strawberry: 'Ttalgi', n1: 'Il', n2: 'I', n3: 'Sam', n4: 'Sa', n5: 'O', n6: 'Yuk', n7: 'Chil', n8: 'Pal', n9: 'Gu', n10: 'Sip', red: 'Ppalgansaek', blue: 'Paransaek', green: 'Choroksaek', yellow: 'Noransaek', black: 'Geomjeongsaek', white: 'Huinsaek', dog: 'Gae', cat: 'Goyangi', lion: 'Saja', tiger: 'Horangi', cow: 'So', horse: 'Mal', how_are_you: 'Eotteoke jinaeseyo', i_am_fine: 'Jal jinaeyo', your_name: 'Ireumi mwoyeyo', where_from: 'Eodiseo oasyeosseoyo' };
tr.Arabic = { hello: 'Marhaban', good_morning: 'Sabah al-khayr', good_afternoon: 'Masa al-khayr', good_evening: 'Masa al-khayr', good_night: 'Tusbih ala khayr', thank_you: 'Shukran', welcome: 'Ahlan wa sahlan', sorry: 'Asif', please: 'Min fadlak', excuse_me: 'Afwan', father: 'Ab', mother: 'Om', brother: 'Akh', sister: 'Ukht', uncle: 'Amm', aunt: 'Amma', grandfather: 'Jadd', grandmother: 'Jadda', son: 'Ibn', daughter: 'Ibna', tea: 'Shaay', water: 'Maa', food: 'Taam', rice: 'Aruzz', milk: 'Haleeb', sugar: 'Sukkar', coffee: 'Qahwa', salt: 'Milh', bread: 'Khubz', doctor: 'Tabeeb', teacher: 'Mualim', lawyer: 'Muhami', engineer: 'Muhandis', police: 'Shurta', farmer: 'Muzari', driver: 'Sayiq', chef: 'Tahi', nurse: 'Mumarrada', apple: 'Tuffaha', banana: 'Mawz', mango: 'Mango', orange: 'Burtuqal', grapes: 'Inab', pineapple: 'Ananas', watermelon: 'Batteekh', papaya: 'Babaya', strawberry: 'Farawla', n1: 'Wahid', n2: 'Ithnan', n3: 'Thalatha', n4: 'Arbaa', n5: 'Khamsa', n6: 'Sitta', n7: 'Sabaa', n8: 'Thamania', n9: 'Tisaa', n10: 'Ashara', red: 'Ahmar', blue: 'Azraq', green: 'Akhdar', yellow: 'Asfar', black: 'Aswad', white: 'Abyad', dog: 'Kalb', cat: 'Qitta', lion: 'Asad', tiger: 'Namir', cow: 'Baqara', horse: 'Husaan', how_are_you: 'Kayfa halak', i_am_fine: 'Ana bikhayr', your_name: 'Ma ismuk', where_from: 'Min ayna anta' };
tr.Thai = { hello: 'Sawadee', good_morning: 'Sawadee Ton Chao', good_afternoon: 'Sawadee Ton Bai', good_evening: 'Sawadee Ton Yen', good_night: 'Ratri Sawat', thank_you: 'Khob Khun', welcome: 'Yin Dee Ton Rap', sorry: 'Kho Tod', please: 'Karuna', excuse_me: 'Kho Tod', father: 'Pho', mother: 'Mae', brother: 'Phi Chai', sister: 'Phi Sao', uncle: 'Lung', aunt: 'Pa', grandfather: 'Poo', grandmother: 'Ya', son: 'Luk Chai', daughter: 'Luk Sao', tea: 'Cha', water: 'Nam', food: 'Ahan', rice: 'Khao', milk: 'Nom', sugar: 'Nam Tan', coffee: 'Kafae', salt: 'Kleua', bread: 'Khanom Pang', doctor: 'Mor', teacher: 'Khru', lawyer: 'Thanai', engineer: 'Witsawakorn', police: 'Tamruat', farmer: 'Chao Rai', driver: 'Khon Khap Rot', chef: 'Phak', nurse: 'Phayaban', apple: 'Aepoen', banana: 'Kluay', mango: 'Mamuang', orange: 'Som', grapes: 'Anggun', pineapple: 'Sapparot', watermelon: 'Taeng Mo', papaya: 'Malakor', strawberry: 'Strawberry', n1: 'Nueng', n2: 'Song', n3: 'Sam', n4: 'Si', n5: 'Ha', n6: 'Hok', n7: 'Chet', n8: 'Paet', n9: 'Kao', n10: 'Sip', red: 'Daeng', blue: 'Fah', green: 'Khiao', yellow: 'Lueang', black: 'Dam', white: 'Khao', dog: 'Ma', cat: 'Maew', lion: 'Singto', tiger: 'Suea', cow: 'Wua', horse: 'Ma', how_are_you: 'Sabai dee mai', i_am_fine: 'Sabai dee', your_name: 'Khun chue arai', where_from: 'Khun ma chak nai' };
tr.Vietnamese = { hello: 'Xin chao', good_morning: 'Chao buoi sang', good_afternoon: 'Chao buoi chieu', good_evening: 'Chao buoi toi', good_night: 'Chuc ngu ngon', thank_you: 'Cam on', welcome: 'Chao mung', sorry: 'Xin loi', please: 'Xin vui long', excuse_me: 'Xin loi', father: 'Cha', mother: 'Me', brother: 'Anh', sister: 'Chi', uncle: 'Chu', aunt: 'Co', grandfather: 'Ong', grandmother: 'Ba', son: 'Con trai', daughter: 'Con gai', tea: 'Tra', water: 'Nuoc', food: 'Thuc an', rice: 'Com', milk: 'Sua', sugar: 'Duong', coffee: 'Ca phe', salt: 'Muoi', bread: 'Banh mi', doctor: 'Bac si', teacher: 'Giao vien', lawyer: 'Luat su', engineer: 'Ky su', police: 'Canh sat', farmer: 'Nong dan', driver: 'Tai xe', chef: 'Dau bep', nurse: 'Y ta', apple: 'Tao', banana: 'Chuoi', mango: 'Xoai', orange: 'Cam', grapes: 'Nho', pineapple: 'Du du', watermelon: 'Dua hau', papaya: 'Dua du', strawberry: 'Dau tay', n1: 'Mot', n2: 'Hai', n3: 'Ba', n4: 'Bon', n5: 'Nam', n6: 'Sau', n7: 'Bay', n8: 'Tam', n9: 'Chin', n10: 'Muoi', red: 'Do', blue: 'Xanh', green: 'Xanh la', yellow: 'Vang', black: 'Den', white: 'Trang', dog: 'Cho', cat: 'Meo', lion: 'Su tu', tiger: 'Ho', cow: 'Bo', horse: 'Ngua', how_are_you: 'Ban co khoe khong', i_am_fine: 'Toi khoe', your_name: 'Ban ten gi', where_from: 'Ban o dau den' };
tr.Indonesian = { hello: 'Halo', good_morning: 'Selamat pagi', good_afternoon: 'Selamat siang', good_evening: 'Selamat malam', good_night: 'Selamat tidur', thank_you: 'Terima kasih', welcome: 'Selamat datang', sorry: 'Maaf', please: 'Tolong', excuse_me: 'Permisi', father: 'Ayah', mother: 'Ibu', brother: 'Kakak laki-laki', sister: 'Kakak perempuan', uncle: 'Paman', aunt: 'Bibi', grandfather: 'Kakek', grandmother: 'Nenek', son: 'Anak laki-laki', daughter: 'Anak perempuan', tea: 'Teh', water: 'Air', food: 'Makanan', rice: 'Nasi', milk: 'Susu', sugar: 'Gula', coffee: 'Kopi', salt: 'Garam', bread: 'Roti', doctor: 'Dokter', teacher: 'Guru', lawyer: 'Pengacara', engineer: 'Insinyur', police: 'Polisi', farmer: 'Petani', driver: 'Supir', chef: 'Koki', nurse: 'Perawat', apple: 'Apel', banana: 'Pisang', mango: 'Mangga', orange: 'Jeruk', grapes: 'Anggur', pineapple: 'Nanas', watermelon: 'Semangka', papaya: 'Pepaya', strawberry: 'Stroberi', n1: 'Satu', n2: 'Dua', n3: 'Tiga', n4: 'Empat', n5: 'Lima', n6: 'Enam', n7: 'Tujuh', n8: 'Delapan', n9: 'Sembilan', n10: 'Sepuluh', red: 'Merah', blue: 'Biru', green: 'Hijau', yellow: 'Kuning', black: 'Hitam', white: 'Putih', dog: 'Anjing', cat: 'Kucing', lion: 'Singa', tiger: 'Macan', cow: 'Sapi', horse: 'Kuda', how_are_you: 'Apa kabar', i_am_fine: 'Saya baik-baik saja', your_name: 'Siapa nama kamu', where_from: 'Kamu dari mana' };
tr.English = { hello: 'Hello', good_morning: 'Good Morning', good_afternoon: 'Good Afternoon', good_evening: 'Good Evening', good_night: 'Good Night', thank_you: 'Thank You', welcome: 'Welcome', sorry: 'Sorry', please: 'Please', excuse_me: 'Excuse Me', father: 'Father', mother: 'Mother', brother: 'Brother', sister: 'Sister', uncle: 'Uncle', aunt: 'Aunt', grandfather: 'Grandfather', grandmother: 'Grandmother', son: 'Son', daughter: 'Daughter', tea: 'Tea', water: 'Water', food: 'Food', rice: 'Rice', milk: 'Milk', sugar: 'Sugar', coffee: 'Coffee', salt: 'Salt', bread: 'Bread', doctor: 'Doctor', teacher: 'Teacher', lawyer: 'Lawyer', engineer: 'Engineer', police: 'Police', farmer: 'Farmer', driver: 'Driver', chef: 'Chef', nurse: 'Nurse', apple: 'Apple', banana: 'Banana', mango: 'Mango', orange: 'Orange', grapes: 'Grapes', pineapple: 'Pineapple', watermelon: 'Watermelon', papaya: 'Papaya', strawberry: 'Strawberry', n1: 'One', n2: 'Two', n3: 'Three', n4: 'Four', n5: 'Five', n6: 'Six', n7: 'Seven', n8: 'Eight', n9: 'Nine', n10: 'Ten', red: 'Red', blue: 'Blue', green: 'Green', yellow: 'Yellow', black: 'Black', white: 'White', dog: 'Dog', cat: 'Cat', lion: 'Lion', tiger: 'Tiger', cow: 'Cow', horse: 'Horse', how_are_you: 'How are you', i_am_fine: 'I am fine', your_name: 'What is your name', where_from: 'Where are you from' };

// Global word pool for distractors when a language has too few words
const GLOBAL_DISTRACTOR_POOL = ['Alpha', 'Beta', 'Gamma', 'Delta', 'Echo', 'Foxtrot', 'Golf', 'Hotel', 'India', 'Juliet', 'Kilo', 'Lima', 'Mike', 'November', 'Oscar', 'Papa', 'Quebec', 'Romeo', 'Sierra', 'Tango', 'Uniform', 'Victor', 'Whiskey', 'X-ray', 'Yankee', 'Zulu'];

function T(lang, key, en) {
  return (tr[lang] && tr[lang][key]) ? tr[lang][key] : en + ' (' + lang + ')';
}

function buildQuizzes(lang, vocabs, difficulty) {
  const quizzes = [];
  // Get all translations for this language as distractor pool
  const allTr = Object.values(tr[lang] || {}).filter(Boolean);

  vocabs.forEach(v => {
    // Get 3 distractors different from correct answer
    let pool = allTr.filter(w => w !== v.word);
    // If not enough, pad with global pool
    while (pool.length < 3) {
      const extra = GLOBAL_DISTRACTOR_POOL[pool.length % GLOBAL_DISTRACTOR_POOL.length] + '_' + lang.slice(0, 2);
      if (!pool.includes(extra)) pool.push(extra);
    }
    const distractors = pool.sort(() => Math.random() - 0.5).slice(0, 3);
    const options = [v.word, ...distractors].sort(() => Math.random() - 0.5);

    // Multiple choice: English → Target language
    quizzes.push({
      type: 'multiple_choice',
      question: 'How do you say "' + v.translation + '" in ' + lang + '?',
      correctAnswer: v.word,
      options: options,
      hint: 'Starts with: ' + v.word[0],
      icon: v.icon || '📖'
    });

    // Listening and fill_blank only for beginner/intermediate (not advanced placeholders)
    if (difficulty !== 'advanced') {
      // Listening: hear the target word, pick the English meaning
      const engPool = vocabs.filter(x => x.translation !== v.translation).map(x => x.translation);
      while (engPool.length < 3) engPool.push('Other');
      const engDistractors = engPool.sort(() => Math.random() - 0.5).slice(0, 3);
      const listeningOptions = [v.translation, ...engDistractors].sort(() => Math.random() - 0.5);
      quizzes.push({
        type: 'listening',
        question: 'What do you hear?',
        audioWord: v.word,
        correctAnswer: v.translation,
        options: listeningOptions,
        hint: 'Listen carefully!',
        icon: v.icon || '🎧'
      });

      // Fill in the blank: given English, type the target language word
      quizzes.push({
        type: 'fill_blank',
        question: 'Fill in the blank: "___ " means "' + v.translation + '" in ' + lang,
        correctAnswer: v.word,
        hint: 'Starts with: ' + v.word[0],
        icon: v.icon || '✏️'
      });
    }
  });

  // Match pairs if >= 3 vocabs
  if (vocabs.length >= 3) {
    const pairs = {};
    vocabs.forEach(v => pairs[v.translation] = v.word);
    quizzes.push({
      type: 'match_pairs',
      question: 'Match the words with their translations',
      leftColumn: vocabs.map(v => v.translation),
      rightColumn: vocabs.map(v => v.word),
      correctPairs: pairs
    });
  }
  return quizzes;
}

function G(lang, key, en, icon) {
  return { word: T(lang, key, en), translation: en, icon: icon || '📖', key: key };
}

function getModules(lang) {
  return [
    {
      courseId: 'beginner_1', courseName: 'Beginner Mastery', difficulty: 'beginner', order: 1, title: 'Greetings', description: 'Learn daily greetings in ' + lang, icon: '👋', xpReward: 15,
      vocabulary: [G(lang, 'hello', 'Hello', '👋'), G(lang, 'good_morning', 'Good Morning', '🌅'), G(lang, 'good_afternoon', 'Good Afternoon', '☀️'), G(lang, 'good_evening', 'Good Evening', '🌆'), G(lang, 'good_night', 'Good Night', '🌙'), G(lang, 'thank_you', 'Thank You', '🙏'), G(lang, 'welcome', 'Welcome', '🎉'), G(lang, 'sorry', 'Sorry', '😔'), G(lang, 'please', 'Please', '��'), G(lang, 'excuse_me', 'Excuse Me', '🙋')]
    },
    {
      courseId: 'beginner_2', courseName: 'Beginner Mastery', difficulty: 'beginner', order: 2, title: 'Family Members', description: 'Learn family words in ' + lang, icon: '👨‍👩‍👧', xpReward: 15,
      vocabulary: [G(lang, 'father', 'Father', '👨'), G(lang, 'mother', 'Mother', '👩'), G(lang, 'brother', 'Brother', '👦'), G(lang, 'sister', 'Sister', '👧'), G(lang, 'uncle', 'Uncle', '🧔'), G(lang, 'aunt', 'Aunt', '👩'), G(lang, 'grandfather', 'Grandfather', '👴'), G(lang, 'grandmother', 'Grandmother', '👵'), G(lang, 'son', 'Son', '🧒'), G(lang, 'daughter', 'Daughter', '🧒')]
    },
    {
      courseId: 'beginner_3', courseName: 'Beginner Mastery', difficulty: 'beginner', order: 3, title: 'Daily Words', description: 'Essential daily words in ' + lang, icon: '🍵', xpReward: 15,
      vocabulary: [G(lang, 'tea', 'Tea', '🍵'), G(lang, 'water', 'Water', '💧'), G(lang, 'food', 'Food', '🍲'), G(lang, 'rice', 'Rice', '🍚'), G(lang, 'milk', 'Milk', '🥛'), G(lang, 'sugar', 'Sugar', '🍯'), G(lang, 'coffee', 'Coffee', '☕'), G(lang, 'salt', 'Salt', '��'), G(lang, 'bread', 'Bread', '🍞')]
    },
    {
      courseId: 'beginner_4', courseName: 'Beginner Mastery', difficulty: 'beginner', order: 4, title: 'Professions', description: 'Learn professions in ' + lang, icon: '��‍⚕️', xpReward: 20,
      vocabulary: [G(lang, 'doctor', 'Doctor', '👨‍⚕️'), G(lang, 'teacher', 'Teacher', '👨‍🏫'), G(lang, 'lawyer', 'Lawyer', '⚖️'), G(lang, 'engineer', 'Engineer', '👷'), G(lang, 'police', 'Police', '👮'), G(lang, 'farmer', 'Farmer', '🧑‍🌾'), G(lang, 'driver', 'Driver', '🚗'), G(lang, 'chef', 'Chef', '👨‍🍳'), G(lang, 'nurse', 'Nurse', '👩‍⚕️')]
    },
    {
      courseId: 'beginner_5', courseName: 'Beginner Mastery', difficulty: 'beginner', order: 5, title: 'Fruits', description: 'Learn fruit names in ' + lang, icon: '🍎', xpReward: 15,
      vocabulary: [G(lang, 'apple', 'Apple', '🍎'), G(lang, 'banana', 'Banana', '🍌'), G(lang, 'mango', 'Mango', '🥭'), G(lang, 'orange', 'Orange', '🍊'), G(lang, 'grapes', 'Grapes', '🍇'), G(lang, 'pineapple', 'Pineapple', '🍍'), G(lang, 'watermelon', 'Watermelon', '🍉'), G(lang, 'papaya', 'Papaya', '🍈'), G(lang, 'strawberry', 'Strawberry', '🍓')]
    },
    {
      courseId: 'beginner_6', courseName: 'Beginner Mastery', difficulty: 'beginner', order: 6, title: 'Numbers 1-10', description: 'Count 1 to 10 in ' + lang, icon: '🔢', xpReward: 15,
      vocabulary: [G(lang, 'n1', 'One', '1️⃣'), G(lang, 'n2', 'Two', '2️⃣'), G(lang, 'n3', 'Three', '3️⃣'), G(lang, 'n4', 'Four', '4️⃣'), G(lang, 'n5', 'Five', '5️⃣'), G(lang, 'n6', 'Six', '6️⃣'), G(lang, 'n7', 'Seven', '7️⃣'), G(lang, 'n8', 'Eight', '8️⃣'), G(lang, 'n9', 'Nine', '9️⃣'), G(lang, 'n10', 'Ten', '🔟')]
    },
    {
      courseId: 'intermediate_1', courseName: 'Intermediate Mastery', difficulty: 'intermediate', order: 1, title: 'Colors', description: 'Learn colors in ' + lang, icon: '🎨', xpReward: 20,
      vocabulary: [G(lang, 'red', 'Red', '🔴'), G(lang, 'blue', 'Blue', '🔵'), G(lang, 'green', 'Green', '🟢'), G(lang, 'yellow', 'Yellow', '🟡'), G(lang, 'black', 'Black', '⚫'), G(lang, 'white', 'White', '⚪')]
    },
    {
      courseId: 'intermediate_2', courseName: 'Intermediate Mastery', difficulty: 'intermediate', order: 2, title: 'Animals', description: 'Learn animal names in ' + lang, icon: '🦁', xpReward: 20,
      vocabulary: [G(lang, 'dog', 'Dog', '🐕'), G(lang, 'cat', 'Cat', '🐈'), G(lang, 'lion', 'Lion', '🦁'), G(lang, 'tiger', 'Tiger', '🐅'), G(lang, 'cow', 'Cow', '🐄'), G(lang, 'horse', 'Horse', '🐎')]
    },
    {
      courseId: 'intermediate_3', courseName: 'Intermediate Mastery', difficulty: 'intermediate', order: 3, title: 'Daily Sentences', description: 'Common phrases in ' + lang, icon: '💬', xpReward: 25,
      vocabulary: [G(lang, 'how_are_you', 'How are you?', '🤔'), G(lang, 'i_am_fine', 'I am fine', '😊'), G(lang, 'your_name', 'What is your name?', '📛'), G(lang, 'where_from', 'Where are you from?', '🌍')]
    },
    {
      courseId: 'advanced_1', courseName: 'Advanced Mastery', difficulty: 'advanced', order: 1, title: 'Conversations', description: 'Real conversations in ' + lang, icon: '🗣️', xpReward: 35,
      vocabulary: [G(lang, 'how_are_you', 'How are you?', '🤔'), G(lang, 'i_am_fine', 'I am fine', '😊'), G(lang, 'your_name', 'What is your name?', '📛'), G(lang, 'where_from', 'Where are you from?', '🌍'), G(lang, 'thank_you', 'Thank You', '🙏'), G(lang, 'welcome', 'Welcome', '🎉'), G(lang, 'sorry', 'Sorry', '😔')]
    },
    {
      courseId: 'advanced_2', courseName: 'Advanced Mastery', difficulty: 'advanced', order: 2, title: 'More Phrases', description: 'More phrases in ' + lang, icon: '📚', xpReward: 35,
      vocabulary: [G(lang, 'good_morning', 'Good Morning', '🌅'), G(lang, 'good_evening', 'Good Evening', '🌆'), G(lang, 'good_night', 'Good Night', '🌙'), G(lang, 'please', 'Please', '🙏'), G(lang, 'excuse_me', 'Excuse Me', '🙋')]
    }
  ];
}

const seedData = async () => {
  try {
    await mongoose.connect(process.env.MONGODB_URI || 'mongodb://localhost:27017/langzy');
    console.log('Connected to MongoDB');
    await Lesson.deleteMany({});
    console.log('Cleared existing lessons');

    for (const lang of languages) {
      const modules = getModules(lang);
      const langLessons = modules.map(m => {
        const vocabs = m.vocabulary.map(v => ({
          word: v.word, translation: v.translation,
          icon: v.icon || '📖',
          example: v.translation + ' = ' + v.word
        }));
        return {
          lessonId: lang.toLowerCase().replace(/ /g, '_') + '_' + m.courseId,
          language: lang,
          courseId: m.courseId,
          courseName: m.courseName,
          difficulty: m.difficulty,
          order: m.order,
          title: m.title,
          description: m.description,
          icon: m.icon,
          xpReward: m.xpReward,
          vocabulary: vocabs,
          grammar: { topic: m.title, explanation: 'Practice ' + m.title + ' in ' + lang },
          quizzes: buildQuizzes(lang, vocabs, m.difficulty)
        };
      });

      await Lesson.insertMany(langLessons);
      console.log('Seeded ' + langLessons.length + ' lessons for ' + lang);
    }
    console.log('All lessons seeded! Total languages: ' + languages.length);
    process.exit(0);
  } catch (error) {
    console.error('Seeding error:', error.message);
    process.exit(1);
  }
};

seedData();
